language: groovy
jdk:
- oraclejdk7
branches:
  only:
  - master
before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- GRAILS_VERSION=`grep '^app\.grails\.version=' ./application.properties | sed -e
  's/^app\.grails\.version=//g'`
- gvm install grails $GRAILS_VERSION || true
before_script:
- mkdir -p ~/.grails; wget -q -O ~/.grails/settings.groovy https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_grails_settings_old.groovy
- MAVEN_REPO="ala-repo-snapshot"; grep '^app\.version=' ./application.properties |
  grep -q "\-SNAPSHOT"; if [ "$?" = "1" ]; then MAVEN_REPO="ala-repo-release"; fi;
script: grails clean && grails refresh-dependencies --non-interactive && grails prod
  war --non-interactive && grails prod maven-deploy --repository=$MAVEN_REPO --non-interactive
env:
  global:
  - secure: gUUGk7va4qLyafJEhDMqkBc2FwvfYO615xvKnwYZd26nd9pune/k9AVmLvOGJ6mBS26OfUCzi+J0qZetY95UctAcCjRX9g0ZuUBksyWNflBoXiW3eC2Ic7b8BCc2lnvAJ39QXV4jtuG83ak8EtQPrmSzbQRgYsKwVCMs/EMATE8=
  - secure: P8aV5E/gRODc7iayg2hwdy7YAtKzdBkioppwCFzcCCfRgwMmz1/IHO5+QZyvIBUx/Bz+0dbV9NoWP0lnq3pnBhiIt18jynv4pw+HwYYPKlANjdISLMKBBj30IE5mduhytFVOpSbcmMUsypvBBunZH2CNglukZF6SMw5uk16UMBQ=
